### ISSUE TITLE
Tekton Triggers updates

### ISSUE THREAD

**Issue by brianxjx** [kabanero-io/draft-guide-jenkins-integration-with-kabanero#24]
By default our pipelines with triggers choose a github hash for tagging the built containers.

We should at a minimum mention document how a hard coded tag could placed in both the jenkinsFile and the triggerbindings.

**Comment by brianxjx** [comment]
I'll be adding a proposed update for the bld&push pipeline that would make it an example for this usecase.

**Comment by jantley-ibm** [comment]
@brianxjx did your updates satisfy this issue?

**Comment by brianxjx** [comment]
Worked with chirp1 on
https://github.com/kabanero-io/guide-jenkins-integration-with-kabanero/pull/23
no add'nl updates needed for the doc
